### PR TITLE
OCPBUGS-43745: Add support for IdleCloseTerminationPolicy (Go http.Client)

### PR DESCRIPTION
**Pull request by frobware**
Introduce logic in desiredRouterDeployment to set the environmentvariable `ROUTER_IDLE_CLOSE_ON_RESPONSE` when the `IdleConnectionTerminationPolicy` field in the IngressController spec is set to `Deferred`. This change enables configuring HAProxy with the `idle-close-on-response` option for better control over idle connection termination behaviour.

Add an e2e test `Test_IdleConnectionTerminationPolicy` to verify the behaviour. 

Requires:
- openshift/api#2102
- openshift/router#639

### CODE REVIEW

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-aws-operator openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-aws-operator openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-aws-operator openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-aws-operator openshift/router#639

**Comment by frobware** [comment]
@alebedev87 this is ready for review when you get chance. We likely need a few test runs to understand whether the new test still flakes.

**Comment by frobware** [comment]
The `e2e-aws-operator-techpreview` job currently fails (and will persistently fail) when testing with the Dynamic Config Manager (DCM) feature enabled on the IngressController for the following reasons:

1. Incorrect Test Actions:
The test setup uses deferredActions even when DCM is enabled. Since DCM supports dynamic updates, deferredActions should be replaced with immediateActions in the test when DCM is detected and configured. Without this change, the test incorrectly assumes a reload-based model, leading to invalid results. Additionally, the test may need to be restructured to ensure both configurations—without DCM and with DCM (where possible)—are appropriately tested.

2. Unexpected 503 Responses:
Even when switching the actions, the test observes 503 responses after a route’s service is switched. The expectation is that with DCM, changes should be applied dynamically without triggering an HAProxy soft-reload. This behaviour may point to:
    - A potential issue with HAProxy server-slots (as we configure them in OpenShift).
    - An interaction between server-slots and the `idle-close-on-response` setting.
    - Or perhaps an outright HAProxy bug. 

All of these failure possibilities need further investigation.

Given these challenges, my proposal is to address this specific test failure (DCM-enabled IngressController x `e2e-aws-operator-techpreview`) as a follow-up PR. This approach ensures that the PR, as it currently stands, would allow us to immediately start the backports for versions 4.18 through 4.14, where the DCM feature is not present.

By applying the following patch to this PR:

```diff
diff --git a/test/e2e/idle_connection_test.go b/test/e2e/idle_connection_test.go
index a92986fd..7943900b 100644
--- a/test/e2e/idle_connection_test.go
+++ b/test/e2e/idle_connection_test.go
@@ -17,6 +17,7 @@ import (
 	corev1 "k8s.io/api/core/v1"
 	apierrors "k8s.io/apimachinery/pkg/api/errors"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/runtime"
 	"k8s.io/apimachinery/pkg/types"
 	"k8s.io/apimachinery/pkg/util/intstr"
 	"k8s.io/apimachinery/pkg/util/wait"
@@ -434,6 +435,11 @@ func Test_IdleConnectionTerminationPolicy(t *testing.T) {
 		ic.Spec.NamespaceSelector = &metav1.LabelSelector{
 			MatchLabels: testNs.Labels,
 		}
+
+		ic.Spec.UnsupportedConfigOverrides = runtime.RawExtension{
+			Raw: []byte(`{"dynamicConfigManager":"true"}`),
+		}
+
 		if err := kclient.Create(context.Background(), ic); err != nil {
 			return nil, fmt.Errorf("failed to create IngressController: %w", err)
 		}
@@ -527,6 +533,8 @@ func Test_IdleConnectionTerminationPolicy(t *testing.T) {
 		},
 	}
 
+	deferredActions = deferredActions
+
 	for _, tc := range []struct {
 		policy  operatorv1.IngressControllerConnectionTerminationPolicy
 		actions []testAction
@@ -537,7 +545,7 @@ func Test_IdleConnectionTerminationPolicy(t *testing.T) {
 		},
 		{
 			policy:  operatorv1.IngressControllerConnectionTerminationPolicyDeferred,
-			actions: deferredActions,
+			actions: immediateActions,
 		},
 	} {
 		tc := tc
```

I see: 


```plaintext
=== NAME  Test_IdleConnectionTerminationPolicy/Deferred
    idle_connection_test.go:616: step 1: Verify the initial response is correctly served by web-service-1
=== NAME  Test_IdleConnectionTerminationPolicy
    idle_connection_test.go:486: [192.168.7.64:48114 -> 44.194.165.3:80] Req: URL=http://44.194.165.3, Host=test-idle-connection-close-deferred-cd8pl.apps.amcdermo-202501170937.devcluster.openshift.com
    idle_connection_test.go:486: [192.168.7.64:48114 <- 44.194.165.3:80] Res: Status=200, Headers=map[Content-Length:[8] Content-Type:[text/plain; charset=utf-8] Date:[Fri, 17 Jan 2025 11:51:28 GMT] Set-Cookie:[ae6d093502b8ac0b43e88840bc28c5ec=b933a9d7fd391aa98d425349f5d08111; path=/; HttpOnly] X-Pod-Name:[web-service-1] X-Pod-Namespace:[idle-connection-close-deferred-cd8pl]]
=== NAME  Test_IdleConnectionTerminationPolicy/Deferred
    idle_connection_test.go:616: step 2: Switch route to web-service-2 and verify Immediate policy ensures new responses are served by web-service-2
=== NAME  Test_IdleConnectionTerminationPolicy
    idle_connection_test.go:496: [192.168.7.64:48114 -> 44.194.165.3:80] Req: URL=http://44.194.165.3, Host=test-idle-connection-close-deferred-cd8pl.apps.amcdermo-202501170937.devcluster.openshift.com
    idle_connection_test.go:496: [192.168.7.64:48114 <- 44.194.165.3:80] Res: Status=503, Headers=map[Cache-Control:[private, max-age=0, no-cache, no-store] Content-Type:[text/html] Pragma:[no-cache]]
=== NAME  Test_IdleConnectionTerminationPolicy/Deferred
    idle_connection_test.go:624: step 2: unexpected response: got "", want "web-service-2"

**Comment by frobware** [comment]
failed to create cluster:

/test e2e-gcp-operator

**Comment by alebedev87** [comment]
Bug for the DCM failure: https://issues.redhat.com/browse/OCPBUGS-48560.

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-aws-operator /openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-azure-operator /openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-aws-operator openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-azure-operator openshift/router#639

**Comment by frobware** [comment]
> /testwith openshift/cluster-ingress-operator/master/e2e-azure-operator [openshift/router#639](https://github.com/openshift/router/pull/639)

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/multi-pr-openshift-cluster-ingress-operator-1182-openshift-router-639-e2e-azure-operator/1880281369716723712/artifacts/e2e-azure-operator/test/build-log.txt

        --- PASS: TestAll/parallel/Test_IdleConnectionTerminationPolicy (0.00s)
            --- PASS: TestAll/parallel/Test_IdleConnectionTerminationPolicy/Immediate (139.28s)
            --- PASS: TestAll/parallel/Test_IdleConnectionTerminationPolicy/Deferred (169.05s)

**Comment by frobware** [comment]
> /testwith openshift/cluster-ingress-operator/master/e2e-aws-operator [openshift/router#639](https://github.com/openshift/router/pull/639)

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/multi-pr-openshift-cluster-ingress-operator-1182-openshift-router-639-e2e-aws-operator/1880281335805775872/artifacts/e2e-aws-operator/test/build-log.txt

        --- PASS: TestAll/parallel/Test_IdleConnectionTerminationPolicy (0.00s)
            --- PASS: TestAll/parallel/Test_IdleConnectionTerminationPolicy/Immediate (186.89s)
            --- PASS: TestAll/parallel/Test_IdleConnectionTerminationPolicy/Deferred (190.00s)

**Comment by frobware** [comment]
> /test e2e-azure-operator /test e2e-aws-operator

Both successful.

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-aws-operator openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-azure-operator openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-gcp-operator openshift/router#639

**Comment by frobware** [comment]
testwith openshift/cluster-ingress-operator/master/e2e-gcp-operator openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-gcp-operator openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-azure-operator openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-aws-operator openshift/router#639

**Comment by frobware** [comment]
`TestAll/parallel/Test_IdleConnectionTerminationPolicy` Successful in e2e-aws-operator, but other e2e tests failed.

/test e2e-aws-operator

File: test/e2e/idle_connection_test.go [hunk 1]
```diff
@@ -0,0 +1,634 @@
...
+					return fmt.Errorf("error fetching latest version of namespace %s: %w", testNs.Name, err)
+				}
+				if err := kclient.Update(context.TODO(), testNs); err != nil {
+					t.Logf("conflict updating namespace %s with labels %s: %v, retrying...", testName, testNs.Labels, err)
+					return err
+				}
+				return nil
+			}); err != nil {
+				t.Fatalf("error updating namespace %s with labels %s: %v", testName, testNs.Labels, err)
+			}
```
Comment (alebedev87) [inline test/e2e/idle_connection_test.go:564]: Should we sacrifice the simplicity of the code (and the test execution time too) for a slightly more complex backport merging? 

```suggestion
			testNs := createNamespaceWithLabels(t, testName, map[string]string{testNs.Name + "-shard": testName})
```

```go
func createNamespace(t *testing.T, name string) {
    return createNamespaceWithLabels(t, name, nil)
}
```

File: test/http2/server.go [hunk 2]
```diff
@@ -21,35 +21,53 @@ func lookupEnv(key, defaultVal string) string {
 	return defaultVal
 }
 
+func respondWithPodInfo(w http.ResponseWriter, response string) {
+	w.Header().Set("x-pod-name", lookupEnv("POD_NAME", "unknown-pod"))
+	w.Header().Set("x-pod-namespace", lookupEnv("POD_NAMESPACE", "unknown-namespace"))
```
Comment (alebedev87) [inline test/http2/server.go:26]: This header is not used in the test.

**Comment by alebedev87** [comment]
@frobware: any particular reason to run multi pr tests?
```
/testwith openshift/cluster-ingress-operator/master/e2e-aws-operator https://github.com/openshift/router/pull/639
```

The router's code was merged 2 weeks ago, it must be in the CI builds since a while now.

File: test/http2/server.go (hunk 2 above)
Comment (frobware) [reply test/http2/server.go:26]: It's there for future consumers.

File: test/e2e/idle_connection_test.go [hunk 3]
```diff
@@ -0,0 +1,634 @@
...
+			switch tc.policy {
+			case operatorv1.IngressControllerConnectionTerminationPolicyImmediate:
+				if localAddresses[1] != localAddresses[2] {
+					t.Fatalf("%s policy: expected steps 2 and 3 to use same connection, but got addresses %s and %s", tc.policy, localAddresses[1], localAddresses[2])
+				}
+			case operatorv1.IngressControllerConnectionTerminationPolicyDeferred:
+				if localAddresses[0] != localAddresses[1] {
+					t.Fatalf("%s policy: expected steps 1 and 2 to use same connection, but got addresses %s and %s", tc.policy, localAddresses[0], localAddresses[1])
+				}
+			}
```
[the remark this answers is not in the document]
Comment (frobware) [reply test/e2e/idle_connection_test.go:631]: Yes, I believe we should fail the test. We unequivocally expect port numbers to remain the same or change depending on which policy we are testing. Without asserting conditions, the HTTP client might automatically create new connections.

File: test/e2e/idle_connection_test.go [hunk 4]
```diff
@@ -0,0 +1,634 @@
...
+					},
+					Env: []corev1.EnvVar{
+						{
+							Name:  "HTTP2_TEST_SERVER_ENABLE_HTTP_LISTENER",
+							Value: "true",
+						},
+						{
+							Name:  "HTTP2_TEST_SERVER_ENABLE_HTTPS_LISTENER",
+							Value: "false",
+						},
```
[the remark this answers is not in the document]
Comment (frobware) [reply test/e2e/idle_connection_test.go:179]: I was being explicit. I prefer the explicitness.

File: test/e2e/idle_connection_test.go [hunk 5]
```diff
@@ -0,0 +1,634 @@
...
+			// verifyExternalIngressController() returns OK from
+			// createIngressController(), CI flakes have been observed where
+			// subsequent HTTP GETs using the ELB hostname (i.e., not an IP
+			// address) fail to resolve. To mitigate these flakes, the ELB
+			// hostname is resolved to an IP address, which is then used
+			// exclusively for HTTP transactions.
+			elbAddress, err := resolveIngressControllerAddress(t, ic)
+			if err != nil {
+				t.Fatalf("test setup failed: %v", err)
+			}
```
[the remark this answers is not in the document]
Comment (frobware) [reply test/e2e/idle_connection_test.go:586]: It prevents a flake. Saves you 3 hours of your life. Why in "just in this test"? This applies to all HTTP transactions for both policies.

**Comment by frobware** [comment]
> @frobware: any particular reason to run multi pr tests?
> 
> ```
> /testwith openshift/cluster-ingress-operator/master/e2e-aws-operator https://github.com/openshift/router/pull/639
> ```
> 
> The router's code was merged 2 weeks ago, it must be in the CI builds since a while now.

No reason; I'm just doing a cut/paste on existing jobs so that I can simultaneously have many tests for our e2e tests. I just want more signal (i.e., more jobs runs) so that we can determine whether we're still flaking. If I don't run these I have to wait 3 hours (which is too long).

File: test/e2e/idle_connection_test.go (hunk 1 above)
Comment (frobware) [reply test/e2e/idle_connection_test.go:564]: Is your suggestion to modify the existing `createNamespace` function? I don't want to make the backports painful. And in a test run that runs three hours I fail to see what a Get/Update will add to the mix.

Comment (frobware) [reply test/e2e/idle_connection_test.go:564]: > for a slightly more complex backport merging?

For me the question answers itself; why go looking for work/

File: test/e2e/idle_connection_test.go [hunk 6]
```diff
@@ -0,0 +1,634 @@
...
+							},
+						},
+						{
+							Name: "POD_NAMESPACE",
+							ValueFrom: &corev1.EnvVarSource{
+								FieldRef: &corev1.ObjectFieldSelector{
+									FieldPath: "metadata.namespace",
+								},
+							},
+						},
```
[the remark this answers is not in the document]
Comment (frobware) [reply test/e2e/idle_connection_test.go]: Done in https://github.com/openshift/cluster-ingress-operator/compare/a34641a00e437c5b1c4196b2b9311692932fcbc2..78321f30d594d4ac892d614eb93e5ac832397b32.

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-aws-operator openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-azure-operator openshift/router#639

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-gcp-operator openshift/router#639

**Comment by frobware** [comment]
`Test_IdleConnectionTerminationPolicy` service pods didn't become ready:

    operator_test.go:4202: error getting pod idle-connection-close-deferred-cmz9b/web-service-1: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline

/test e2e-gcp-operator

**Comment by frobware** [comment]
> `Test_IdleConnectionTerminationPolicy` service pods didn't become ready:
> 
> ```
> operator_test.go:4202: error getting pod idle-connection-close-deferred-cmz9b/web-service-1: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
> ```
> 
> /test e2e-gcp-operator

This was my bad push: https://github.com/openshift/cluster-ingress-operator/commit/bde8da38f8774e3a175d5154c04863aab9076f77. Running tests again.

**Comment by frobware** [comment]
I don't see any flakes in latest run of the e2e tests.

**Comment by frobware** [comment]
/testwith openshift/cluster-ingress-operator/master/e2e-gcp-operator openshift/router#639
/testwith openshift/cluster-ingress-operator/master/e2e-azure-operator openshift/router#639
/testwith openshift/cluster-ingress-operator/master/e2e-aws-operator openshift/router#639

File: test/e2e/idle_connection_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (frobware) [reply test/e2e/idle_connection_test.go]: These expectations outline the guarantees provided by haproxy. Having these assertions in place helps validate that we maintain the same behaviour in haproxy 2.6 (when backporting) but also helps to ensure the behaviour remains consistent when we upgrade to 3.0.

**Comment by frobware** [comment]
e2e-aws-ovn-serial and e2e-hypershift are failing in an empty PR: https://github.com/openshift/cluster-ingress-operator/pull/1185#issuecomment-2608163284

**Comment by lihongan** [comment]
Did pre-merge test and looks good.
```
##  no "option idle-close-on-response" in default router pod
$ oc -n openshift-ingress-operator get ingresscontroller/default -oyaml | yq .spec.idleConnectionTerminationPolicy
Immediate
$ oc -n openshift-ingress get deployment/router-default -oyaml | grep IDLE
(null)
$ oc -n openshift-ingress exec router-default-595897545-kfczn -- cat haproxy.config | grep idle
(null)

## create custom ingresscontroller and update spec.idleConnectionTerminationPolicy
$ oc -n openshift-ingress-operator get ingresscontroller/test -oyaml | yq .spec.idleConnectionTerminationPolicy
Immediate

$ oc -n openshift-ingress-operator patch ingresscontroller/test --type=merge -p '{"spec":{"idleConnectionTerminationPolicy":"Deferred"}}'
ingresscontroller.operator.openshift.io/test patched

$ oc -n openshift-ingress get deployment/router-test -oyaml | grep IDLE -A1
        - name: ROUTER_IDLE_CLOSE_ON_RESPONSE
          value: "true"

$ oc -n openshift-ingress exec router-test-6c756c4ff8-gdv4s -- cat haproxy.config | grep idle -B4
  frontend public
    
  bind :80
  mode http
  option idle-close-on-response
--
frontend fe_sni
  # terminate ssl on edge
  bind unix@/var/lib/haproxy/run/haproxy-sni.sock ssl crt /var/lib/haproxy/router/certs/default.pem crt-list /var/lib/haproxy/conf/cert_config.map accept-proxy no-alpn
  mode http
  option idle-close-on-response
--
frontend fe_no_sni
  # terminate ssl on edge
  bind unix@/var/lib/haproxy/run/haproxy-no-sni.sock ssl crt /var/lib/haproxy/router/certs/default.pem accept-proxy no-alpn
  mode http
  option idle-close-on-response
```

/label qe-approved

**Comment by frobware** [comment]
The e2e-aws-ovn-serial job is failing with "Image signature workflow can push a signed image to openshift registry and verify it" - related links:

- https://github.com/openshift/origin/pull/29466
- https://redhat-internal.slack.com/archives/C01CQA76KMX/p1737106812413019
